- cmd/agent/main.go
- cmd/agent/service.go
把剩余的flag加到service命令里了，以处理一些人在安装脚本里加上其它参数装不了的问题
> Support more flags in the service command

- pkg/monitor/monitor.go
> make atomicStoreFloat64 safe

- pkg/monitor/monitor.go
> fix: temperatureStat will stack up

- cmd/agent/edit.go
- cmd/agent/main.go
- cmd/agent/service.go
- go.mod
- go.sum
- pkg/gpu/stat/stat_darwin.go
- pkg/gpu/stat/stat_freebsd.go
- pkg/gpu/stat/stat_linux.go
- pkg/gpu/stat/stat_windows.go
- pkg/monitor/monitor.go
- pkg/pty/pty_windows.go
- pkg/util/util.go
另外将 `cmd/agent/main.go` 中部分服务相关代码移回了 `cmd/agent/service.go`
> service: logging to syslog

- pkg/gpu/gpu.go
- pkg/gpu/gpu_darwin.go
- pkg/monitor/monitor.go
- pkg/pty/pty_windows.go
for better flexibility (although may not be useful)
other changes:
- add spaces between error messages
> refactor(pty): switch to using interface

- cmd/agent/edit.go
- cmd/agent/main.go
- model/model.go
- pkg/monitor/monitor.go
- pkg/monitor/myip.go
- pkg/util/util.go
增加新选项 `--temperature` 和 `--slient`
- `--temperature` 添加以启用温度监控（现在默认禁用）
- `-q` `--slient` 添加以禁用日志输出
> feat: make logging and temperature monitoring optional

- .github/workflows/agent.yml
- .github/workflows/sync.py
- .github/workflows/sync.yml
同步最新release及附件到gitee
需要额外配置一下GITEE_TOKEN，在gitee-私人密钥那里创建
默认是同步到naibahq/agent，也需要创建一下
> ci: sync release to gitee

- cmd/agent/main.go
看来原作者原先是想默认设置一个恢复选项，但是条件没处理好，这里便手动设置了一个
> fix: add recovery option for windows service

- pkg/gpu/stat/stat_windows.go
使用Pdh直接获取GPU占用率，大幅提升性能 & 降低CPU占用率
> feat(gpu): use pdh on Windows

- cmd/agent/main.go
fix “错误的服务监控上报”
~~发版是否可以等一段时间，等有实质性的更新再发~~
> chore: missing return

- .github/workflows/sync.py
> ci: only keep the latest release

- .github/dependabot.yml
- go.mod
- go.sum
> downgrade some dependencies to the compatible version

- pkg/monitor/monitor.go
保持显示的一致性（目前macos arm64是无序的，显示效果不太行）
> improve: sort sensor names & add an ignore list for sensors

- cmd/agent/main.go
- pkg/monitor/myip.go
- pkg/util/util.go
- pkg/utls/roundtripper.go
- pkg/utls/roundtripper_test.go
https://pkg.go.dev/google.golang.org/grpc@v1.64.1#DialContext
> grpc: update deprecated method

- pkg/monitor/cpu/cpu.go
Close https://github.com/nezhahq/agent/issues/96
> fix(cpu): detect number of cores correctly on all platforms

- cmd/agent/main.go
- cmd/agent/main_test.go
- pkg/util/http.go
- pkg/util/util.go
- pkg/util/util_test.go
解析ip api先使用系统的dns服务器
简化了一些逻辑
把自带的国内dns服务器都替换掉了，感觉国内的不一定靠谱
> fix: using system dns servers first

- pkg/monitor/monitor.go
- pkg/monitor/nic/nic.go
- pkg/util/util.go
Fix https://github.com/nezhahq/agent/issues/137
> fix: possible integer overflow

- pkg/util/util.go
更改 ua 使其更容易被检测到
Close https://github.com/nezhahq/agent/issues/145
> change the ua of crawling client

- cmd/agent/main.go
- model/config.go
- model/task.go
- pkg/logger/logger.go
- pkg/monitor/monitor.go
- pkg/monitor/myip.go
https://github.com/nezhahq/nezha/pull/980
> feat: edit server config online

- cmd/agent/main.go
- pkg/util/util.go
Fix https://github.com/nezhahq/agent/issues/173
> fix: self-update will crash system on windows

- cmd/agent/main.go
原本 reportState 只有 10 秒超时时间，而其中获取 IP 等非汇报操作可能会占用较长时间，进而直接导致超时重连，因此将处理超时的操作细分到了每个 收/发 操作
> improve timeout logic
